apiVersion: v1
kind: Service
metadata:
  name: sleep
spec:
  ports:
  - port: 9015
    targetPort: 80
    protocol: TCP
  selector:
    app: sleep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  labels:
    app: sleep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep
        image: uhub.service.ucloud.cn/safehouse/php-apache:1.1
        ports:
        - containerPort: 80
#      - name: sleep-1
#        image: ubuntu
#        ports:
#        - containerPort: 8080


