apiVersion: v1
kind: Service
metadata:
  name: harbor
  namespace: test-xmdataopen-manager
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Endpoints
metadata:
  name: harbor
  namespace: test-xmdataopen-manager
subsets:
- addresses:
  - ip: 192.168.255.40
  ports:
  - port: 80
    protocol: TCP