apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: sf-repo
metadata:
  name: test-sandbox-eliot
  namespace: test-istio-universal
  labels:
    k8s-app: test-sandbox-eliot
---
apiVersion: v1
kind: Service
metadata:
  name: test-sandbox-eliot
  namespace: test-istio-universal
  labels:
    app: test-sandbox-eliot
    role: test
spec:
  selector:
    app: test-sandbox-eliot
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-sandbox-eliot
  namespace: test-istio-universal
  labels:
    app: test-sandbox-eliot
    role: test
    user: eliot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-sandbox-eliot
      role: test
      user: eliot
  template:
    metadata:
      labels:
        app: test-sandbox-eliot
        role: test
        user: eliot
    spec:
      serviceAccountName: test-sandbox-eliot
      containers:
      - name: test-sandbox-eliot
        image: uhub.service.ucloud.cn/safehouse/network-multitool:latest
        ports:
        - containerPort: 8080