apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s: 
        service:
          ports:
          - name: status-port
            nodePort: 31857
            port: 15021
            protocol: TCP
            targetPort: 15021
          - name: http2
            nodePort: 30756
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            nodePort: 31774
            port: 443
            protocol: TCP
            targetPort: 8443
          - name: tls
            nodePort: 32267
            port: 15443
            protocol: TCP
            targetPort: 15443
        #   - name: tcp-istiod
        #     nodePort: 30150
        #     port: 15012
        #     protocol: TCP
        #     targetPort: 15012
        #   - name: tcp-dns-tls
        #     nodePort: 32710
        #     port: 853
        #     protocol: TCP
        #     targetPort: 8853
  hub: uhub.service.ucloud.cn/safehouse
  values:
    global:
      imagePullSecrets:
      - sf-repo
      imagePullPolicy: IfNotPresent
      multiCluster:
        clusterName: main0
      network: network1

      meshNetworks:
        network1:
          endpoints:
          - fromRegistry:  main0
          gateways:
          - address: 106.75.29.147  #gateay的外网地址
            port: 31774             #gateway 443端口对应的

        network2:
          endpoints:
          - fromRegistry: remote0
          gateways:
          - address: 106.75.52.243
            port: 32246

      meshExpansion:
        enabled: true