apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uwebtop-guacd-pvc
  namespace: universal-developer-common
  labels:
    app: uwebtop-guacd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: course-nfs-storage