apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: universal-developer-common
  labels:
    app: guacd
spec:
  ports:
  - port: 4822
    targetPort: 4822
  selector:
    app: guacd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: universal-developer-common
  labels:
    app: guacd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
      - image: uhub.service.ucloud.cn/safehouse/guacd:latest
        name: guacd
        ports:
        - containerPort: 4822
          name: guacd
        volumeMounts:
        - name: uwebtop-persistent-storage
          mountPath: /record
      volumes:
      - name: uwebtop-persistent-storage
        persistentVolumeClaim:
          claimName: uwebtop-guacd-pvc