apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: universal-baiduai-common
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306


---
kind: Endpoints
apiVersion: v1
metadata:
  namespace: universal-baiduai-common
  name: db
subsets:
- addresses:
  - ip: 10.9.82.73
  ports:
  - port: 3306