apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uwebtop-guacd-pvc
  namespace: uwebtop
  labels:
    app: uwebtop-guacd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: storageclass-default
