apiVersion: v1
kind: Service
metadata:
  name: uwebtop-guacd-svc
  namespace: uwebtop
  labels:
    app: uwebtop-guacd-svc
spec:
  type: NodePort
  ports:
  - port: 4822
    targetPort: 4822
  selector:
    app: uwebtop-guacd