kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: offline-server-user-data-pvc
  labels:
    app: offline-server-user-data-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: course-nfs-storage
  selector:
    matchLabels:
      app: offlineserver-user-data