#对应gateway的virtualService要和gateway在一个namespace
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: edge-ucloud
  namespace: test-istio-universal
spec:
  gateways:
  - ucloud-gateway
  hosts:
  - 'edge.sf.ucloud.cn'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: sleep.project-caribou.svc.cluster.local
        port:
          number: 9015