apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-hostpath
  labels:
    type: local
spec:
  storageClassName: hostpv-test
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data"