apiVersion: v1
kind: Service
metadata:
  name: uwebtop-manager-svc
  namespace: uwebtop
  labels:
    app: uwebtop-manager-svc
spec:
  type: NodePort
  ports:
  - port: 8099
    targetPort: 8081
  selector:
    app: uwebtop-manager