apiVersion: v1
kind: Service
metadata:
  name: uwebtop-worker-svc
  namespace: uwebtop
  labels:
    app: uwebtop-worker-svc
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30010
  selector:
    app: uwebtop-worker