apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-test-dopx-manager
  namespace: test-dopx-manager
  labels:
    k8s-app: fluentd-logging-test-dopx-manager
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging-test-dopx-manager
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging-test-dopx-manager
        version: v1
    spec:
      serviceAccountName: fluentd-es-test-dopx-manager
      containers:
      - name: fluentd
        image: uhub.service.ucloud.cn/safehouse/fluentd:v1.9-4
        args:
        - -c
        - "/etc/fluent/fluent.conf"

        resources:
          limits:
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /data/docker/containers
          readOnly: true
        - name: fluent-conf
          mountPath: /etc/fluent/fluent.conf
          subPath: fluent.conf

      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /data/docker/containers
      - name: fluent-conf
        configMap:
          name: fluent-conf