apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policyrole
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - example