apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: policyrolebinding
  namespace: uwebtop
roleRef:
  kind: Role
  name: policyrole
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize specific service accounts:
- kind: ServiceAccount
  name: default
  namespace: uwebtop