apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-encrypt
  labels:
    app: nginx-encrypt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-encrypt
  template:
    metadata:
      labels:
        app: nginx-encrypt
    spec:
      containers:
      - name: decrypt-data
        image: uhub.service.ucloud.cn/safehouse/gocryptfs:1.1
        command: ['sh', '-c', 'echo "123456" | gocryptfs -q -- /dataset/cipher /dataset/plain;ls /dataset/plain;df -h;touch /dataset/init.txt; sleep 300000;']
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - name: nginx-encrypt-volume
          mountPath: /dataset
          mountPropagation: Bidirectional
      - name: nginx-encrypt
        image: uhub.service.ucloud.cn/safehouse/nginx:1.0
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - name: nginx-encrypt-volume
          mountPath: /dataset
          mountPropagation: Bidirectional
      volumes:
      - name: nginx-encrypt-volume
        persistentVolumeClaim:
          claimName: nginx-encrypt-volume-pvc