apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-encrypt
  labels:
    app: nginx-encrypt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-encrypt
  template:
    metadata:
      labels:
        app: nginx-encrypt
    spec:
      containers:
      - name: nginx-encrypt
        image: uhub.service.ucloud.cn/safehouse/gocryptfs:1.1
        command: ['sh', '-c',"sleep 30000000"]
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command: ['sh', '-c', 'echo "123456" | gocryptfs -q -- /dataset/cipher /dataset/plain']
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-encrypt-volume
          mountPath: /dataset
      volumes:
      - name: nginx-encrypt-volume
        persistentVolumeClaim:
          claimName: nginx-encrypt-volume-pvc