apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: devops-role
  namespace: devops
  labels:
    key1: roletest

rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
