apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
     discoveryAddress: "istiod-remote.istio-system.svc:31344"
  values:
    global:
      hub: uhub.service.ucloud.cn/safehouse
      imagePullSecrets:
      - sf-repo
      # The remote cluster's name and network name must match the values specified in the
      # mesh network configuration of the primary cluster.
      multiCluster:
        clusterName: remote0
      network: network1

      # Replace ISTIOD_REMOTE_EP with the the value of ISTIOD_REMOTE_EP set earlier.
      remotePilotAddress: 192.168.255.222
  components:
   ingressGateways:
   - name: istio-ingressgateway
     enabled: false