apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-all-pods
subjects:
- kind: ServiceAccount
  name: eliot # 名称区分大小写
  namespace: default
roleRef:
  kind: ClusterRole
  name: all-pods-reader
  apiGroup: rbac.authorization.k8s.io