apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # "" 指定核心 API 组
  resources: ["pods"]
  #resourceNames: ["sleep-6589549cbb-9l2gm"]
  verbs: ["get", "watch", "list"]
