apiVersion: v1
kind: Service
metadata:
  name: jupyter-proxy
  namespace: test-baiduai-manager
spec:
  type: NodePort
  selector:
    app: dynamic-proxy
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30181
    targetPort: 8001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-proxy
  namespace: test-baiduai-manager
  labels:
    app: dynamic-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-proxy
  template:
    metadata:
      labels:
        app: dynamic-proxy
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      containers:
      - name: nginx
        image: nginx:1.7.9
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
