apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx0-deployment
  namespace: test-xmai-manager
  labels:
    app: nginx0-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx0
  template:
    metadata:
      labels:
        app: nginx0
    spec:
      containers:
      - name: nginx
        image: uhub.service.ucloud.cn/safehouse/nginx:1.0
        env:
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PUBLIC_RSA_KEY
          valueFrom:
            secretKeyRef:
              name: public-rsa-key
              key: public_rsa_key
        - name: PRIVATE_RSA_KEY
          valueFrom:
            secretKeyRef:
              name: private-rsa-key
              key: private_rsa_key
        ports:
        - containerPort: 80
        volumeMounts:
          - name : public-rsa-key
            mountPath: /etc/secret-volume-public
          - name: private-rsa-key
            mountPath: /etc/secret-volume-private
      # The secret data is exposed to Containers in the Pod through a Volume.
      volumes:
      - name: public-rsa-key
        secret:
          secretName: public-rsa-key
      - name: private-rsa-key
        secret:
          secretName: private-rsa-key