apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: test-xmdataopen-manager
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis
  namespace: test-xmdataopen-manager
subsets:
- addresses:
  - ip: 192.168.255.116
  ports:
  - port: 6379
    protocol: TCP