apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: sf-repo
metadata:
  name: formal-data
  namespace: test-istio-universal
  labels:
    k8s-app: formal-data
---
apiVersion: v1
kind: Service
metadata:
  name: formal-data
  namespace: test-istio-universal
  labels:
    app: formal-data
spec:
  selector:
    app: formal-data
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: formal-data
  namespace: test-istio-universal
  labels:
    app: formal-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formal-data
  template:
    metadata:
      labels:
        app: formal-data
    spec:
      serviceAccountName: formal-data
      containers:
      - name: formal-data
        image: uhub.service.ucloud.cn/safehouse/gin-upgrade-b0addd3:1.0
        ports:
        - containerPort: 8080