apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: sf-repo
- name: ops-repo
metadata:
  name: test-data
  namespace: test-istio-universal
  labels:
    k8s-app: test-data
---

apiVersion: v1
kind: Service
metadata:
  name: test-data
  namespace: test-istio-universal
  labels:
    app: test-data
spec:
  selector:
    app: test-data
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-data
  namespace: test-istio-universal
  labels:
    app: test-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-data
  template:
    metadata:
      labels:
        app: test-data
    spec:
      serviceAccountName: test-data
      containers:
      - name: test-data
        image: uhub.service.ucloud.cn/safehouse/gin-upgrade-b0addd3:1.0
        ports:
        - containerPort: 8080