apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitflow-starter
  namespace: uwebtop
  labels:
    app: gitflow-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitflow-starter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitflow-starter
    spec:
      imagePullSecrets:
      - name: sf-repo
      containers:
      - image: "uhub.service.ucloud.cn/safehouse/spy-go.gitflow-starter:master-101"
        name: gitflow-starter
        env:
        - name: GUACD_SERVICE_ADDR
          value: ""
        - name: MASTER_ADDR
          value: ""
        - name: RUN_MODE
          value: "debug"
        ports:
        - containerPort: 8080
          name: gitflow-starter
#        volumeMounts:
#        - name: gitflow-starter-config-map
#          mountPath: /etc/gitflow-starter-svc/conf
#      volumes:
#      - name: gitflow-config-map
#        configMap:
#          name: gitflow-config