apiVersion: v1
kind: Service
metadata:
  name: git-starter-svc
  namespace: uwebtop
  labels:
    app: git-starter-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: gitflow-starter