apiVersion: v1
kind: Service
metadata:
  name: gitflow-st-copy
  namespace: uwebtop
  labels:
    app: gitflow-st-copy
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: gitflow-st-copy