apiVersion: v1
metadata:
  name: dynamic-masker-env
  namespace: test-xmdataopen-manager
kind: ConfigMap
data:
  U_MYSQL_HOST: db
  U_MYSQL_USER: dy_masker_test_xm_dataopen
  U_MYSQL_DATABASE: dy_masker_test_xm_dataopen
  U_MYSQL_PASSWORD: ucloud.cn
  U_MYSQL_PORT: "3309"






