apiVersion: v1
metadata:
  name: rcmanager-env
  namespace: test-xmdataopen-manager
kind: ConfigMap
data:
  U_MYSQL_HOST: db
  U_MYSQL_USER: rcmanager_test_xm_dataopen
  U_MYSQL_DATABASE: rcmanager_test_xm_dataopen
  U_MYSQL_PASSWORD: ucloud.cn
  U_MYSQL_PORT: "3309"
  U_RCMAN_BASE_URL: http://console.pre.ucloudstack.com/api
  U_RCMAN_PROJECT_ID: org-idskha
  U_RCMAN_REGION: cn
  U_RCMAN_ZONE: zone-01
  U_RCMAN_VM_TYPE: ComputeSet01
  U_RCMAN_CHARGE_TYPE: Dynamic
  U_RCMAN_BOOT_DISK_TYPE: StorageSet01
  U_RCMAN_BOOT_DISK_SIZE: "40"
  U_RCMAN_DATA_DISK_TYPE: StorageSet02
  U_RCMAN_DATA_DISK_SIZE: "100"
  U_RCMAN_PUBLIC_KEY: xxxx
  U_RCMAN_PRIVATE_KEY: xxxx
  U_RCMAN_SANDBOX_USERNAME: root






