apiVersion: v1
metadata:
  name: uwebtop-env
  namespace: test-xmdataopen-manager
kind: ConfigMap
data:
  U_MYSQL_HOST: db
  U_MYSQL_USER: uwebtop_test_xm_dataopen
  U_MYSQL_DATABASE: uwebtop_test_xm_dataopen
  U_MYSQL_PASSWORD: ucloud.cn
  U_MYSQL_PORT: "3309"





