apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: sf-repo
metadata:
  name: ext-auth-service
  namespace: test-istio-universal
  labels:
    k8s-app: ext-auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: ext-auth-service
  namespace: test-istio-universal
  labels:
    app: ext-auth-service
spec:
  selector:
    app: ext-auth-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-auth-service
  namespace: test-istio-universal
  labels:
    app: ext-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-auth-service
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: ext-auth-service
    spec:
      serviceAccountName: ext-auth-service
      containers:
      - name: ext-auth-service
        image: uhub.service.ucloud.cn/safehouse/ext_auth:latest
        ports:
        - containerPort: 8080