apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: ${DEPLOYMENT_NAMESPACE}
spec:
  externalName: ${MINIO_EXTERNAL_NAME}
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  sessionAffinity: None
  type: ExternalName
