apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: ${DEPLOYMENT_NAMESPACE}
spec:
  ports:
  - port: 3309
    protocol: TCP
    targetPort: 3309
  type: ClusterIP

---
kind: Endpoints
apiVersion: v1
metadata:
  namespace: ${DEPLOYMENT_NAMESPACE}
  name: db
subsets:
- addresses:
  - ip: ${MYSQL_HOST}
  ports:
  - port: ${MYSQL_PORT}