apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ${DEPLOYMENT_NAMESPACE}
spec:
  ports:
  - port: ${REDIS_PORT}
    protocol: TCP
    targetPort: ${REDIS_PORT}
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis
  namespace: ${DEPLOYMENT_NAMESPACE}
subsets:
- addresses:
  - ip: ${REDIS_HOST}
  ports:
  - port: ${REDIS_PORT}
    protocol: TCP