kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: readonly-user-data-pvc
  labels:
    app: readonly-user-data-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: course-nfs-storage
  selector:
    matchLabels:
      app: readonly-user-data