apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-es-test-dopx-follower
  namespace: test-dopx-follower
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-es-test-dopx-follower
  labels:
    k8s-app: fluentd-es-test-dopx-follower
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-es-test-dopx-follower
  labels:
    k8s-app: fluentd-es-test-dopx-follower
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: fluentd-es-test-dopx-follower
  namespace: test-dopx-follower
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-es-test-dopx-follower
  apiGroup: ""