kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ksm-can-be-accessed-by-my-app
  namespace: uwebtop
spec:
  podSelector:
    matchLabels:
      app: uwebtop-nginx
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          project: default
    - podSelector:
        matchLabels:
          app: uwebtop-nginx-v2
    ports:
    - protocol: TCP
      port: 10301