kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ksm-can-be-accessed-by-my-app
  namespace: uwebtop
spec:
  podSelector:
    matchLabels:
      app: uwebtop-nginx
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: my-app-that-needs-access-to-ksm
    ports:
    - protocol: TCP
      port: 10301