---
apiVersion: v1
kind: Service
metadata:
  name: sleep-v2
spec:
  ports:
  - port: 9015
    targetPort: 80
    protocol: TCP
  selector:
    app: sleep-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-v2
  labels:
    app: sleep-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep-v2
  template:
    metadata:
      labels:
        app: sleep-v2
    spec:
      containers:
      - name: sleep-v2
        image: uhub.service.ucloud.cn/safehouse/network-multitool:1.0
        ports:
        - containerPort: 80
  
