apiVersion: v1
kind: Service
metadata:
  name: sleep-minio-v2
spec:
  ports:
  - port: 9015
    targetPort: 8080
    protocol: TCP
  selector:
    app: sleep-minio-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-minio-v2
  labels:
    app: sleep-minio-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep-minio-v2
  template:
    metadata:
      labels:
        app: sleep-minio-v2
    spec:
      containers:
      - name: sleep-minio-v2
        image: uhub.service.ucloud.cn/safehouse/network-multitool:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: sleep-minio-pvc
          mountPath: /var/lib/www/html

      volumes:
      - name: sleep-minio-pvc
        persistentVolumeClaim:
          claimName: sleep-minio-pvc
          readOnly: false
